### ISSUE TITLE
执行install.sh报错

### ISSUE THREAD

**Issue by catusax** [Arondight/sudodev#8]
窝用的arch
窝在运行install.sh时报错
sudo sh install.sh
install.sh: 第 6 行:source: build.sh: 文件未找到
脚本改为sh build.sh install却可以正常运行
还有，以非root身份运行build会退出，这样就得重启终端。
窝等会给你pull一下

**Comment by Arondight** [comment]
非常感谢报告issues，请不要手动指定解释器运行`install.sh`。

试试按照[README.md](https://github.com/Arondight/sudodev/blob/ad2251294f4eff3536269d087a6064eeadafb5a2/README.md) 写的一样执行：

``` shell
./install.sh
```

或者

``` shell
./build.sh
```

如果问题复现，请回复。

另外我在`zsh` 和`bash` 中均无法复现这个问题，麻烦在回复中说明一下可以复现的操作，非常感谢～

**Comment by catusax** [comment]
好吧，解释器的原因，窝一直以为bash和sh没区别。。。。。。

**Comment by Arondight** [comment]
麻烦贴一下指令的结果

```
file $(which sh)
```

在Arch Linux 下，`sh` 应该是指向`bash` 的软连接，Ubuntu 下则指向`dash`，但是目前来看这都是正常的，所以麻烦贴一下指令结果，看看你的系统中`sh` 到底指向什么，这个问题我用Arch Linux 和Ubuntu 无法复现……

**Comment by catusax** [comment]
/usr/bin/sh: symbolic link to bash

**Comment by Arondight** [comment]
我试着复现了一下这个问题，得出的结论是：当环境变量`$PATH` 中不存在当前目录`.` 的时候，手动指定解释器就会出现这个错误。

这并不是解释器的问题，而是$PATH 的不同导致无法在当前目录中搜索`build.sh`。

另外非root 权限运行`build.sh` 即退出的情况没有发现，考虑了一下各种情况，你可能是在当前环境中执行了脚本中的语句：

``` shell
source build.sh
```

如果是这样的话，这是`shell` 的特性而非脚本的缺陷，关于这一点可以参考你shell 解释器的手册。

在zsh 的zshbuiltins 手册中（`man zshbuiltins`）有如下描述：

> ```
>    . file [ arg ... ]
>           Read commands from file and execute them in the current shell environment.
>    source file [ arg ... ]
>           Same as `.', except that the current directory is always searched and is always searched first, before directories in $path.
> ```
